# This is a basic workflow to help you get started with Actions

name: CI
env:
  BUILD_DIR: "/home/azureuser/git-build-dir"
  OUTPUT_DIR:  "output-virtualbox-iso"
  VIRTUAL_BOX_PATH: /home/azureuser/VirtualBox\ VMs/glasswall-proxy/
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'diagrams/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  build-and-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of taskdjuss that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE/s-k8-releases, so your job can access it  
    - uses: actions/checkout@v2
      with:
        path: s-k8-releases

    - name: remove previously created OVA and clear direcotries
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
           rm -rf ${{ env.VIRTUAL_BOX_PATH }} ${{ env.BUILD_DIR }}/*

  
    - name: copy code to the server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        local: ${{ github.workspace }}/s-k8-releases
        remote: ${{ env.BUILD_DIR }}/s-k8-releases

    - name: Build the OVA on a remote VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        timeout: 10000s
        command_timeout: 10000s
        script: |
           cd ${{ env.BUILD_DIR }}/s-k8-releases &&  git clone --single-branch --branch develop --recursive https://github.com/k8-proxy/k8-reverse-proxy/
           tar czvf revproxy.tar.gz -C ${{ env.BUILD_DIR }}/s-k8-releases/k8-reverse-proxy/stable-src/ .
           packer build box.json 

    - name: Upload the OVA to S3
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        timeout: 1000s
        script: |
           mv ${{ env.BUILD_DIR }}/s-k8-releases/${{ env.OUTPUT_DIR }}/glasswall-proxy.ova ${{ env.BUILD_DIR }}/s-k8-releases/${{ env.OUTPUT_DIR }}/glasswall-proxy-${{ github.sha }}.ova
           aws s3 cp ${{ env.BUILD_DIR }}/s-k8-releases/${{ env.OUTPUT_DIR }}/glasswall-proxy-${{ github.sha }}.ova s3://glasswall-proxy-ova/
          
