# This is a basic workflow to help you get started with Actions

name: CI
#env:
 # REPOSITORY: glasswallicap.azurecr.io
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ update/workflow ]
    paths-ignore: 
      - 'diagrams/**'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'diagrams/**'    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  build-and-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   
   # - uses: actions/checkout@v2
  
    - name: Build the OVA on a remote VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        timeout: 10000s
        script: |
           cd /home/azureuser/git-build-dir &&  git clone https://github.com/k8-proxy/s-k8-releases.git
           cd /home/azureuser/git-build-dir/s-k8-releases && git clone --recursive https://github.com/filetrust/k8-reverse-proxy.git
           tar czvf revproxy.tar.gz -C /home/azureuser/git-build-dir/s-k8-releases/k8-reverse-proxy/ /home/azureuser/git-build-dir/s-k8-releases/reverse-proxy-icap-docker/
           packer build box.json -force

    - name: Upload the OVA to S3
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        timeout: 1000s
        script: |
          echo test